/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.app.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.remote.app.model.CustomElementPortletEntry;
import com.liferay.remote.app.service.CustomElementPortletEntryLocalService;
import com.liferay.remote.app.uad.constants.RemoteAppUADConstants;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the custom element portlet entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link CustomElementPortletEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCustomElementPortletEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<CustomElementPortletEntry> {

	@Override
	public void autoAnonymize(
			CustomElementPortletEntry customElementPortletEntry, long userId,
			User anonymousUser)
		throws PortalException {

		if (customElementPortletEntry.getUserId() == userId) {
			customElementPortletEntry.setUserId(anonymousUser.getUserId());
			customElementPortletEntry.setUserName(anonymousUser.getFullName());
		}

		customElementPortletEntryLocalService.updateCustomElementPortletEntry(
			customElementPortletEntry);
	}

	@Override
	public void delete(CustomElementPortletEntry customElementPortletEntry)
		throws PortalException {

		customElementPortletEntryLocalService.deleteCustomElementPortletEntry(
			customElementPortletEntry);
	}

	@Override
	public Class<CustomElementPortletEntry> getTypeClass() {
		return CustomElementPortletEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return customElementPortletEntryLocalService.
			getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return RemoteAppUADConstants.
			USER_ID_FIELD_NAMES_CUSTOM_ELEMENT_PORTLET_ENTRY;
	}

	@Reference
	protected CustomElementPortletEntryLocalService
		customElementPortletEntryLocalService;

}