/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.app.uad.anonymizer;

import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.remote.app.model.RemoteCustomElementEntry;
import com.liferay.remote.app.service.RemoteCustomElementEntryLocalService;
import com.liferay.remote.app.uad.constants.RemoteAppUADConstants;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the remote custom element entry UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link RemoteCustomElementEntryUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseRemoteCustomElementEntryUADAnonymizer
	extends DynamicQueryUADAnonymizer<RemoteCustomElementEntry> {

	@Override
	public void autoAnonymize(
			RemoteCustomElementEntry remoteCustomElementEntry, long userId,
			User anonymousUser)
		throws PortalException {

		if (remoteCustomElementEntry.getUserId() == userId) {
			remoteCustomElementEntry.setUserId(anonymousUser.getUserId());
			remoteCustomElementEntry.setUserName(anonymousUser.getFullName());
		}

		remoteCustomElementEntryLocalService.updateRemoteCustomElementEntry(
			remoteCustomElementEntry);
	}

	@Override
	public void delete(RemoteCustomElementEntry remoteCustomElementEntry)
		throws PortalException {

		remoteCustomElementEntryLocalService.deleteRemoteCustomElementEntry(
			remoteCustomElementEntry);
	}

	@Override
	public Class<RemoteCustomElementEntry> getTypeClass() {
		return RemoteCustomElementEntry.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return remoteCustomElementEntryLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return RemoteAppUADConstants.
			USER_ID_FIELD_NAMES_REMOTE_CUSTOM_ELEMENT_ENTRY;
	}

	@Reference
	protected RemoteCustomElementEntryLocalService
		remoteCustomElementEntryLocalService;

}