/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.remote.app.uad.display;

import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.remote.app.model.CustomElementPortletEntry;
import com.liferay.remote.app.service.CustomElementPortletEntryLocalService;
import com.liferay.remote.app.uad.constants.RemoteAppUADConstants;
import com.liferay.user.associated.data.display.BaseModelUADDisplay;

import java.io.Serializable;

import java.util.List;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the CustomElementPortletEntry UAD display.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom methods should be put in
 * {@link CustomElementPortletEntryUADDisplay}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCustomElementPortletEntryUADDisplay
	extends BaseModelUADDisplay<CustomElementPortletEntry> {

	@Override
	public CustomElementPortletEntry get(Serializable primaryKey)
		throws PortalException {

		return customElementPortletEntryLocalService.
			getCustomElementPortletEntry(Long.valueOf(primaryKey.toString()));
	}

	@Override
	public String[] getDisplayFieldNames() {
		return new String[] {"name", "tagName"};
	}

	@Override
	public Class<CustomElementPortletEntry> getTypeClass() {
		return CustomElementPortletEntry.class;
	}

	@Override
	protected long doCount(DynamicQuery dynamicQuery) {
		return customElementPortletEntryLocalService.dynamicQueryCount(
			dynamicQuery);
	}

	@Override
	protected DynamicQuery doGetDynamicQuery() {
		return customElementPortletEntryLocalService.dynamicQuery();
	}

	@Override
	protected List<CustomElementPortletEntry> doGetRange(
		DynamicQuery dynamicQuery, int start, int end) {

		return customElementPortletEntryLocalService.dynamicQuery(
			dynamicQuery, start, end);
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return RemoteAppUADConstants.
			USER_ID_FIELD_NAMES_CUSTOM_ELEMENT_PORTLET_ENTRY;
	}

	@Reference
	protected CustomElementPortletEntryLocalService
		customElementPortletEntryLocalService;

}